scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
  remote_write:
  - url: "http://victoriametrics-nodeport-service:8428/api/v1/write"

- job_name: 'kubernetes-nodes'
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
